spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
mybatis:
  mapper-locations:
    classpath:
      mapper/*.xml
server:
  port: 8888